### Index
GET http://localhost:3000/users

### Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "test_name"
}

### Update
PATCH http://localhost:3000/users/2
Content-Type: application/json

{
  "last_name": ""
}